# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Documentudy
brief-intro: UNIX & Linux Kernel
baseurl: "/documentudy" # the subpath of your site, e.g. /blog
url: "https://soopsaram.com/documentudy" # the base hostname & protocol for your site

plugins:
  - jekyll-feed
description: uNIX & Linux Kernel
author: Soopsaram

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: jihuun 
github_username:  jihuun
email: jihuun.k@gmail.com

description_footer: soopsaram

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: jihuun

# statistic analysis 
google_analytics_id: UA-206788906-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: /category/
tag_dir: /tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
